spring.application.name=demo

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/workforce-os

keycloak.server-url=http://localhost:9090
keycloak.realm=workforce-os
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin